### ISSUE TITLE
make a docker container

### ISSUE THREAD

**Issue by oerbilgin** [biorack/magi#31]
Just realized that the blast step calls a bash script.... this will probably break on a windows machine? having a docker container would be much cleaner

**Comment by benbowen** [comment]
There are some good hints here: https://github.com/biorack/pathway_tools_docker
Basically, this one sets up a linux environment with appropriate packages and then runs a script.

The nice thing here is that you can change the 

```
RUN <command>
```

at the end to be whatever you want when doing 

```
docker run -t <tagged container> <command>
```

and it will override the command in the Dockerfile

**Comment by benbowen** [comment]
maybe some useful stuff here: https://github.com/jupyter/docker-stacks

**Comment by oerbilgin** [comment]
having some major issues getting rdkit import to work.
```
Traceback (most recent call last):
  File "../../workflow/magi_workflow_20170519.py", line 225, in <module>
    import workflow_helpers as mg
  File "/magi/workflow/workflow_helpers.py", line 32, in <module>
    from rdkit import Chem
  File "/miniconda/envs/magi/lib/python2.7/site-packages/rdkit/Chem/__init__.py", line 28, in <module>
    from rdkit.Chem.rdmolops import *
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory
```
... but at least i finally got the conda environment to build in the docker image

**Comment by oerbilgin** [comment]
PR #32
